services:
  - type: web
    name: vizzy-chat
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn vizzychat.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
